#!/bin/sh

# fix permissions
chown -R root:root /opt/safejumperplus/netdown
chown -R root:root /opt/safejumperplus/safejumperplusservice
chown -R root:root /opt/safejumperplus/openvpn

if [ -x /bin/systemctl ]; then
    systemctl enable safejumperplus
    systemctl start safejumperplus
fi

#DEBHELPER#
exit 0
